### ISSUE TITLE
USER STORIES:  Add comments to posts

### ISSUE THREAD

**Issue by EddieCodeHub** [EddieCodeHub/Nerd_News#4]
As a **logged in user** I can **add a comment to a post** so that **i can start a discussion about the post.**

**Acceptance Criteria**

- AC1: comment section labelled so user knows where to comment 

- AC2: text box under label for user to type comment in

- AC3: comment loaded to database and shown below text box in the "comment section"

**Tasks**

- [x] T1: Create Comment model and connect to the database.

- [ ] T2: Create News page View and connect to the database.

- [ ] T3: Connect Comment model to View
