### ISSUE TITLE
USER STORIES: Open a Post

### ISSUE THREAD

**Issue by EddieCodeHub** [EddieCodeHub/Nerd_News#5]
As a **user** I can **click on a post** so that **i can read the full post and comment section.**

**Acceptance Criteria**

- AC1: user can click on post to see the full text and comment section

- AC2: user can click on the comment thread to view them

**Tasks**

- [x] T1: Create News page view and connect to the database.

- [x] T2: Create Comment model and connect to the database and view.

- [ ] T3: Create post_detail view and connect to the news page view
