### ISSUE TITLE
USER STORIES: Admin manage posts/comments

### ISSUE THREAD

**Issue by EddieCodeHub** [EddieCodeHub/Nerd_News#7]
As an **Admin** I can **delete unsuitable posts and comments** so that **the page remains professional and doesn't turn toxic**

**Acceptance Criteria**

- AC1: Admin can delete posts from any user

- AC2: Admin can delete comments from any user

**Tasks**

- [x] T1: Create Superuser account.

- [x] T2: Create News_Post model and connect to database.

- [x] T3: Create Comment model and connect to database.
